version: 0.2

phases:
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/*.jar
    - target/surefire-reports/*.txt
    - target/surefire-reports/*.xml   
    - target/failsafe-reports/*.txt
    - target/failsafe-reports/*.xml
  discard-paths: no