version: 0.2

phases:
  build:
    commands:
      - mvn install

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  secondary-artifacts:
    surefire-reports:
      files:
        - target/surefire-reports/*.txt
        - target/surefire-reports/*.xml
      discard-paths: no
    failsafe-reports:
      files:
        - target/failsafe-reports/*.txt
        - target/failsafe-reports/*.xml
      discard-paths: no